### ISSUE TITLE
Grey windows appears then disappears

### ISSUE THREAD

**Issue by currall** [DarioSamo/sm64rt#2]
Game won't load, when i launch the exe this grey window appears for half a second then vanishes.

In event viewer i get some error with KERNELBASE.dll, idk if thats relevant

![explorer_3PYzYNMkal](https://user-images.githubusercontent.com/29579820/117196724-c090eb80-adde-11eb-9f4b-7cc454a59f5b.png)

**Comment by DarioSamo** [comment]
Can you try any of the following?

1) Make sure your drivers are up to date.
2) Run the game using the windows terminal (e.g. powershell) and see if anything relevant comes up.

**Comment by currall** [comment]
1. GPU Drivers are up to date
2. Launches as expected, no error in powershell or anything
3. Ryzen 5 3600, RTX 2060, 16GB 3200 RAM

**Comment by HHasashi** [comment]
Wanted to add that I also have the same problem, nearly the same specs (R7 2700x, 16GB 3200, base RTX 2060).
Also checked that my GPU drivers are up to date and the game launches as expected, no error in Windows PowerShell or anything.
Thanks in advance !

**Comment by DarioSamo** [comment]
Alright, let's do some further tests:

4. Can you check if this sample runs for you? [rt64sample.zip](https://github.com/DarioSamo/sm64rt/files/6430404/rt64sample.zip)
5. What is your Windows 10 version? (check with winver command)
6. If you're familiar with running gdb, posting the backtrace would help as well (from MSYS2, you can go to build/<region_pc>/ and run "gdb <sm64 exe>", type "run" and Enter when it starts, and once it crashes, you can print the backtrace with "backtrace" and enter.

**Comment by Nama** [comment]
I was too lazy to upgrade, so I'm on 466.11 and it works. Maybe try downgrading if nothing else works.
Ryzen 7 2700
RTX 2070
Win10 20H2 19042.928

**Comment by currall** [comment]
4. Sample also crashed, same as the game
5. Version 1809

**Comment by HHasashi** [comment]
The sample does not work, same problem as with RT64, gray screen then crashes.
I did the backtracing and got this : 

#0  0x00007ffde70b9689 in RaiseException ()
   from /c/Windows/System32/KERNELBASE.dll
#1  0x00007ffdcc7f6220 in _CxxThrowException ()
   from /c/Windows/SYSTEM32/VCRUNTIME140.dll
#2  0x00007ffdbc15964c in ?? () from /home/Heuss/sm64ex/build/us_pc/rt64lib.dll
#3  0x00007ffdbc15bfa5 in rt64lib!RT64_CreateDevice ()
   from /home/Heuss/sm64ex/build/us_pc/rt64lib.dll
#4  0x00007ff6ca5fa749 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

I use Windows 10 LTSC version 1809 (other RTX games such as Quake RTX or BF5 works with my PC btw).
I'm on 466.27.

**Comment by currall** [comment]
> The sample does not work, same problem as with RT64, gray screen then crashes.
> I did the backtracing and got this :
> 
> #0 0x00007ffde70b9689 in RaiseException ()
> from /c/Windows/System32/KERNELBASE.dll
> #1 0x00007ffdcc7f6220 in _CxxThrowException ()
> from /c/Windows/SYSTEM32/VCRUNTIME140.dll
> #2 0x00007ffdbc15964c in ?? () from /home/Heuss/sm64ex/build/us_pc/rt64lib.dll
> [sm64pc#3](https://github.com/sm64pc/sm64ex/issues/3) 0x00007ffdbc15bfa5 in rt64lib!RT64_CreateDevice ()
> from /home/Heuss/sm64ex/build/us_pc/rt64lib.dll
> [sm64pc#4](https://github.com/sm64pc/sm64ex/pull/4) 0x00007ff6ca5fa749 in ?? ()
> Backtrace stopped: previous frame inner to this frame (corrupt stack?)
> 
> I use Windows 10 LTSC version 1809 (other RTX games such as Quake RTX or BF5 works with my PC btw).
> I'm on 466.27.

I get a very similar error, definitely the same DLL. I wonder if it's caused by ltsc, I use that too and it doesn't work yet it works on 20h2 apparently?

**Comment by DarioSamo** [comment]
I do think this might be because of the Windows version actually, as RT64 is compiled with a newer version of the Windows SDK.

I don't mean to force you to upgrade, but it sounds like the most likely solution here.

**Comment by DarioSamo** [comment]
Alternatively, you can try building RT64 yourselves on the older SDK and see if it works, but I don't know if theres any code changes that will break it.

**Comment by HHasashi** [comment]
You use LTSC too ? Then maybe that's the problem. This, or maybe our Windows version (1809) is too old for the game to run ?
But that will be weird as other RTX games runs well and this version supports DXR well enough.
If upgrading is really the solution, like you said, then that will be impossible as the latest LTSC Win is 1809.
I don't think I have the skill to build it myself tho, thanks for the help anyway !

**Comment by DarioSamo** [comment]
Well, it's not really a matter of the DXR version, more like a Windows SDK version. Let me check if I can build that simple in a lower version and see if it fixes the problem.

**Comment by Llennpie** [comment]
I'm on 20H2 (OS Build 19042.928). Same issue here.

**Comment by DarioSamo** [comment]
> 
> 
> I'm on 20H2 (OS Build 19042.928). Same issue here.

Can you confirm whether any of the other steps posted so far help at all in tracking down the issue?

**Comment by HHasashi** [comment]
Thanks man, I really appreciate the effort !

**Comment by DarioSamo** [comment]
> 
> 
> Well, it's not really a matter of the DXR version, more like a Windows SDK version. Let me check if I can build that simple in a lower version and see if it fixes the problem.

Well, this seems like a nogo, as the memory allocation library by AMD requires the latest version to build properly (at least from a quick attempt).

Then again, someone on 20H2 has posted that they have the same issue, so I can't say that's the issue yet.

**Comment by Llennpie** [comment]
> Can you confirm whether any of the other steps posted so far help at all in tracking down the issue?

I have the latest drivers, so I can attempt to compile RT64 myself. Which Windows 10 SDK version should I use? Older or newer?

**Comment by Llennpie** [comment]
Also, here's my GDB info.
```
(gdb) run
Starting program: D:\msys\home\user\sm64rt\build\us_pc\sm64.us.f3dex2e.exe
[New Thread 13176.0x1cc8]
[New Thread 13176.0x2144]
[New Thread 13176.0x1b3c]
[New Thread 13176.0x1100]
[New Thread 13176.0x1488]
[New Thread 13176.0x1354]
[New Thread 13176.0x2b28]
[Thread 13176.0x2b28 exited with code 0]
[New Thread 13176.0x1964]
[Thread 13176.0x1964 exited with code 0]
[New Thread 13176.0x2d70]
[New Thread 13176.0x1a78]
gdb: unknown target exception 0xe06d7363 at 0x7ffca56c4b59

Thread 1 received signal ?, Unknown signal.
0x00007ffca56c4b59 in RaiseException ()
   from C:\Windows\System32\KernelBase.dll
(gdb)
```

**Comment by DarioSamo** [comment]
> 
> 
> > Can you confirm whether any of the other steps posted so far help at all in tracking down the issue?
> 
> I have the latest drivers, so I can attempt to compile RT64 myself. Which Windows 10 SDK version should I use? Older or newer?

Personally I use version 10.0.19041.0.

If you do try building RT64 yourself, you can launch the sample in debug mode and see what the call stack says on VS2019. That'd certainly help a lot.

**Comment by DarioSamo** [comment]
> 
> 
> I'm on 20H2 (OS Build 19042.928). Same issue here.

By the way, can you confirm what GPU do you have?

So far everyone with problems has an RTX 2060 I believe.

**Comment by DarioSamo** [comment]
@HHasashi @currall @Llennpie Are you all by any chance laptop users? Do you have some sort of option that allows you to choose the preferred GPU for an application?

**Comment by HHasashi** [comment]
Absolutely not, since the R7 2700x is a desktop CPU, and doesn't have any integrated GPU, thus the same for Mr. Currall too.
The only GPU we can use then is our 2060 :/

**Comment by DarioSamo** [comment]
> 
> 
> Absolutely not, since the R7 2700x is a desktop CPU, and doesn't have any integrated GPU, thus the same for Mr. Currall too.
> The only GPU we can use then is our 2060 :/

Alright, I've gotten confirmation from another user with an RTX 2060 at least that it does run on their desktop system as well. So I think we can rule that out for now.

I'll try to see if I can get some information regarding the Driver and Windows version.

**Comment by DarioSamo** [comment]
One desktop user using Windows version 2004 and driver 456.71 has confirmed this works on their RTX 2060.

**Comment by Llennpie** [comment]
I've built the RT64 sample project. Upon launching the .exe, I get the same grey window and crash. Here's the output:

![image](https://user-images.githubusercontent.com/44985633/117235342-89c5d000-adf4-11eb-828d-073c69de3a51.png)

Hopefully this helps.

**Comment by DarioSamo** [comment]
@Llennpie Do you think you could run it from the Visual Studio 2019 debugger instead (open solution and press F5, make sure to set up the sample project as the "Startup" project first) and see if the output Window has anything of interest?

I think the view may have failed to create due to an exception, but it's not printed to the regular console.

**Comment by Nightcaat** [comment]
>Are you all by any chance laptop users? Do you have some sort of option that allows you to choose the preferred GPU for an application?

Also a laptop user and was experiencing the same issue, setting a preference in Settings worked :)

![image](https://user-images.githubusercontent.com/26909213/117314554-de993300-ae54-11eb-8b12-a71727941755.png)

**Comment by HHasashi** [comment]
Do you think that a background process could actually be the cause (such as LivelyWallpaper, TaskbarX, RivaTuner/Afterburner, F.lux, Geforce Experience etc...) ?

**Comment by Nama** [comment]
Probably not, but try?
I have MSI Afterburner without Rivertuner running and also GF Experience (btw, it doesn't recognizes as a game, so the FPS counter etc. dont work D:) and its working.

**Comment by HHasashi** [comment]
Yeah no luck again :/

**Comment by HHasashi** [comment]
I get those 2 errors, even tho dxwebsetup says that I have the latest DX version installed.
2060 GPUs supports DX12 too, and my drivers are up-to-date (466.27).

![error 1](https://user-images.githubusercontent.com/83731767/117552856-3b137280-b04e-11eb-8fde-c7dc17c09198.PNG)
![error 2](https://user-images.githubusercontent.com/83731767/117552855-3a7adc00-b04e-11eb-8749-cc86a87270cd.PNG)

**Comment by DarioSamo** [comment]
@HHasashi Seems like I made a small mistake when formatting the error message, think you can redownload and try it again? Just updated it so it prints the error code instead.

**Comment by erherhh4herh** [comment]
![image](https://user-images.githubusercontent.com/17937909/117553479-de00c800-b01f-11eb-92ee-22c7d49292c2.png)

This is what I get. I have the grey window bug as well. It should be noted I'm on an older version of windows (1903), and my nvidia driver is 461.40. I'm updating my nvidia drivers to test, I'll upload the result.

**Comment by DarioSamo** [comment]
MSDN defines that error code as this:

```0x80004002 - E_NOINTERFACE No such interface supported```

Can't say I understand what exactly would trigger this, but I will investigate it some more. It's starting to sound to me like it's related to the Windows 10 version in that particular case though.

**Comment by HHasashi** [comment]
I tried it and got the same error code as "erherhh4herh".
Thanks for your effort.

**Comment by erherhh4herh** [comment]
I updated to 466.27, and I get the same error.

**Comment by DarioSamo** [comment]
I don't think I can do much more other than ask you to try updating Windows 10 I guess.

I'm aware you've said that other RTX software works, but those were probably developed with older versions of the SDK, and I downloaded the SDK around August 2020. I do not have any other alternative than going back and reimplementing it on older SDKs, and the code might not even be compatible.

Given you're likely to have trouble with other software that uses these newer SDKs in the future, my recommendation is to just update. I'm not sure I can manage the effort in sticking to older versions for supporting such a long gap in releases.

**Comment by erherhh4herh** [comment]
I'll try updating, I would prefer not to because Microsoft is pretty anal about forcing updates, and have broken things many times before. Is it possible to set a specific sdk version when building with the make command?

**Comment by DarioSamo** [comment]
RT64 is built separately from sm64rt.

You can set the Windows SDK version in RT64 from Visual Studio on the project configuration, but it causes compilation errors. And most of them aren't even on my code, but on AMD's Memory Allocator that this library relies on (which is a really good solution to handling efficient memory creation in D3D12).

**Comment by Nama** [comment]
I guess DirectX 12.1 is supported on Windows 10 20H1 and later.

**Comment by HHasashi** [comment]
I can't update my Windows unless I switch editions (latest LTSC is 1809)

**Comment by erherhh4herh** [comment]
I updated to 20H2 and it works now!

**Comment by HHasashi** [comment]
Is there anyone using LTSC Win10 who got the game running w/o problems ?

**Comment by DarioSamo** [comment]
> 
> 
> Is there anyone using LTSC Win10 who got the game running w/o problems ?

I don't think there will be. I just double checked the SDK version I'm using and it only supports 2004 and above. So that explains the error easily.

Only way to get this running on 1809 would be to downgrade the SDK and rewrite any code that breaks it.

**Comment by HHasashi** [comment]
You think it is a tedious process ?
Do you think you can do it please ?

**Comment by DarioSamo** [comment]
It requires rewriting code that isn't mine but rather from AMD, so I don't think I can do it. Sorry.

**Comment by HHasashi** [comment]
Nah that's ok, I really appreciate the time and effort thank you : )

**Comment by DarioSamo** [comment]
I guess just to not leave it in such a bad note: it is more likely a Vulkan backend will work on LTSC. I don't know how far away a Vulkan version of RT64 is, but with D3D12 for now I'm afraid it's Microsoft's way or the highway.

**Comment by DarioSamo** [comment]
Since there's now some more proper error handling shown at startup, we can close this one I guess and separate it into different issues if needed.
